name: QuasarCommand
author: Quasar
version: 1.0.0
api: 4.0.0
main: Command\Main

commands:
  heal:
    usage: /heal 
    description: "heal"
    permission: heal.cmd
  feed:
    usage: /feed 
    description: "feed"
    permission: feed.cmd
  speed:
    usage: /speed 
    description: "speed"
    permission: speed.cmd
  uphealth:
    usage: /uphealth
    description: "Ajoute de la vie"
    permission: uph.cmd

permissions:
  heal.cmd:
    default: op
  feed.cmd:
    default: true
  speed.cmd:
    default: op
  uph.cmd:
    default:   op

